---
- name: create cni folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  loop:
    - /opt/cni/bin
    - /opt/cni/config
  become: true

- name: extract plugins
  ansible.builtin.unarchive:
    remote_src: true
    src: "https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-{{ pkg_arch_map[ansible_architecture] }}-v1.0.0.tgz"
    dest: "/opt/cni/bin"
  become: true
