---
- name: get facts
  setup:
  when: "'create' in ansible_run_tags"

- name: update apt cache
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: "'Ubuntu' == ansible_distribution"

- name: setup fail2ban (apt)
  ansible.builtin.apt:
    update_cache: true
    name: fail2ban
    state: latest
  become: true
  when: "'Ubuntu' == ansible_distribution"

- name: setup fail2ban (yum)
  ansible.builtin.yum:
    update_cache: true
    name: fail2ban
    state: latest
  become: true
  when: "ansible_distribution in ['Rocky', 'RedHat', 'CentOS']"
