---
- name: Set systemd-resolved template
  ansible.builtin.template:
    src: resolved.conf.j2
    dest: /etc/systemd/resolved.conf
    mode: 0644
  become: true

- name: restart systemd-resolved
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  become: true

- name: link /etc/resolv.conf
  ansible.builtin.file:
    src: /run/systemd/resolve/resolv.conf
    path: /etc/resolv.conf
    state: link
    force: true
  become: true
  when: "'Rocky' == ansible_distribution"
