---
- name: start and enable loki
  ansible.builtin.service:
    name: loki
    state: started
    enabled: true
  become: true

- name: restart loki
  ansible.builtin.service:
    name: loki
    state: restarted
  become: true
